server:
  port: 8081
  servlet:
    context-path: /employee

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cts_db
    username:  root
    password:  root
    driver-class-name: com.mysql.cj.jdbc.Driver